-- AI Suggestions — one cached "morning brief" per user per day.
-- Isolated, additive table: nothing else references it. Generated by the daily
-- cron (POST /admin/generate-suggestions) and on-demand by GET /api/ai-suggestions.
CREATE TABLE IF NOT EXISTS ai_suggestions (
  user_id      uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  for_date     date        NOT NULL,
  payload      jsonb       NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, for_date)
);
CREATE INDEX IF NOT EXISTS idx_ai_suggestions_date ON ai_suggestions(for_date);
